server:
  port: 8002
spring:
  application:
    name: gateway
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
zuul:
  routes:
    courseservice:
      path: /book/**
      service-id: lh-mock