server:
  port: 8080
spring:
  application:
    name: lh-mock
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    password: root
    username: root
    
    url: ${SPRING_DATASOURCE_URL}
    driverClassName:  com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        session_factory:
          interceptor : com.lh.mock.model.CustomInterceptor
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
