spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShaharBarMoshe/ConfigData
  application:
    name: config
server:
  port: 8001
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    hostname: localhost 
    

    